// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using POC.Multitenant.Data.Contexts;

#nullable disable

namespace POC.Multitenant.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("POC.Multitenant.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "João",
                            TenantId = new Guid("5c09ac75-68e5-496d-af13-0b8d3df96b6f")
                        },
                        new
                        {
                            Id = 2,
                            Name = "Maria",
                            TenantId = new Guid("5c09ac75-68e5-496d-af13-0b8d3df96b6f")
                        },
                        new
                        {
                            Id = 3,
                            Name = "João",
                            TenantId = new Guid("80ccf544-68f8-4b8a-bcb7-5becf05cac4a")
                        },
                        new
                        {
                            Id = 4,
                            Name = "Maria",
                            TenantId = new Guid("80ccf544-68f8-4b8a-bcb7-5becf05cac4a")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
